

services:

  db:
    restart: always
    image: postgres
    container_name: main_arisen_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=21master28admin06
      - POSTGRES_DB=arisen_database
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # не трогать - для линукса

  pgadmin:
      image: dpage/pgadmin4
      container_name: pg-dashboard
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: test@test.com
        PGADMIN_DEFAULT_PASSWORD: 1234
      restart: always


volumes:
  postgres_data: 

