export const Categories: string[] = [
  "Кухня", 
  "Природа", 
  "Увлечения", 
  "Страшилки", 
  "Психолог", 
  "Школа", 
  "Игры", 
  "Путешествия", 
  "Веселье", 
  "Животные"
];

export const user = {
    name: "Qua11ra",
    email: "m@example.com",
  avatar: "/images/dashboardBackground.png",
  description: "Разработчик и энтузиаст технологий. Люблю создавать интересные проекты и изучать новые технологии.",
    persona: "user persona"
};

export const popularBots = [
  {
    id: "popular-1",
    name: "Популярный бот 1",
    description: "Один из самых популярных ботов с высоким рейтингом и множеством активных пользователей",
    author: "popular_author_1",
    image: "/api/placeholder/200/160",
    chatsCount: 4500,
    tags: ["популярный", "топ"],
    rating: 4.8,
    isPopular: true,
  },
  {
    id: "popular-2",
    name: "Популярный бот 2",
    description: "Один из самых популярных ботов с высоким рейтингом и множеством активных пользователей",
    author: "popular_author_2",
    image: "/api/placeholder/200/160",
    chatsCount: 3800,
    tags: ["популярный", "топ"],
    rating: 4.7,
    isPopular: true,
  },
  {
    id: "popular-3",
    name: "Популярный бот 3",
    description: "Один из самых популярных ботов с высоким рейтингом и множеством активных пользователей",
    author: "popular_author_3",
    image: "/api/placeholder/200/160",
    chatsCount: 3200,
    tags: ["популярный", "топ"],
    rating: 4.6,
    isPopular: true,
  },
  {
    id: "popular-4",
    name: "Популярный бот 4",
    description: "Один из самых популярных ботов с высоким рейтингом и множеством активных пользователей",
    author: "popular_author_4",
    image: "/api/placeholder/200/160",
    chatsCount: 2900,
    tags: ["популярный", "топ"],
    rating: 4.5,
    isPopular: true,
  },
  {
    id: "popular-5",
    name: "Популярный бот 5",
    description: "Один из самых популярных ботов с высоким рейтингом и множеством активных пользователей",
    author: "popular_author_5",
    image: "/api/placeholder/200/160",
    chatsCount: 2600,
    tags: ["популярный", "топ"],
    rating: 4.4,
    isPopular: true,
  },
  {
    id: "popular-6",
    name: "Популярный бот 6",
    description: "Один из самых популярных ботов с высоким рейтингом и множеством активных пользователей",
    author: "popular_author_6",
    image: "/api/placeholder/200/160",
    chatsCount: 2400,
    tags: ["популярный", "топ"],
    rating: 4.3,
    isPopular: true,
  },
  {
    id: "popular-7",
    name: "Популярный бот 7",
    description: "Один из самых популярных ботов с высоким рейтингом и множеством активных пользователей",
    author: "popular_author_7",
    image: "/api/placeholder/200/160",
    chatsCount: 2200,
    tags: ["популярный", "топ"],
    rating: 4.2,
    isPopular: true,
  },
  {
    id: "popular-8",
    name: "Популярный бот 8",
    description: "Один из самых популярных ботов с высоким рейтингом и множеством активных пользователей",
    author: "popular_author_8",
    image: "/api/placeholder/200/160",
    chatsCount: 2000,
    tags: ["популярный", "топ"],
    rating: 4.1,
    isPopular: true,
  }
];

export const newBots = [
  {
    id: "new-1",
    name: "Новый бот 1",
    description: "Недавно добавленный бот с современными функциями и возможностями",
    author: "new_author_1",
    image: "/api/placeholder/200/160",
    chatsCount: 450,
    tags: ["новый", "свежий"],
    isNew: true,
    lastActive: "Сегодня",
  },
  {
    id: "new-2",
    name: "Новый бот 2",
    description: "Недавно добавленный бот с современными функциями и возможностями",
    author: "new_author_2",
    image: "/api/placeholder/200/160",
    chatsCount: 380,
    tags: ["новый", "свежий"],
    isNew: true,
    lastActive: "Сегодня",
  },
  {
    id: "new-3",
    name: "Новый бот 3",
    description: "Недавно добавленный бот с современными функциями и возможностями",
    author: "new_author_3",
    image: "/api/placeholder/200/160",
    chatsCount: 320,
    tags: ["новый", "свежий"],
    isNew: true,
    lastActive: "Сегодня",
  },
  {
    id: "new-4",
    name: "Новый бот 4",
    description: "Недавно добавленный бот с современными функциями и возможностями",
    author: "new_author_4",
    image: "/api/placeholder/200/160",
    chatsCount: 290,
    tags: ["новый", "свежий"],
    isNew: true,
    lastActive: "Сегодня",
  },
  {
    id: "new-5",
    name: "Новый бот 5",
    description: "Недавно добавленный бот с современными функциями и возможностями",
    author: "new_author_5",
    image: "/api/placeholder/200/160",
    chatsCount: 260,
    tags: ["новый", "свежий"],
    isNew: true,
    lastActive: "Сегодня",
  },
  {
    id: "new-6",
    name: "Новый бот 6",
    description: "Недавно добавленный бот с современными функциями и возможностями",
    author: "new_author_6",
    image: "/api/placeholder/200/160",
    chatsCount: 240,
    tags: ["новый", "свежий"],
    isNew: true,
    lastActive: "Сегодня",
  }
];