# Generated by Django 5.1.6 on 2025-03-02 20:22

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='bots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botname', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('public_desc', models.TextField(max_length=2000)),
                ('scenario', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='user_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to=main.models.user_directory_path)),
                ('personas', models.FileField(upload_to=main.models.user_directory_path)),
                ('chats', models.FileField(upload_to=main.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.auth')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_files')),
            ],
        ),
    ]
