# Generated by Django 5.1.6 on 2025-03-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botname', models.TextField(max_length=256)),
                ('public_description', models.TextField(max_length=2048)),
                ('description', models.TextField(max_length=8192)),
                ('avatar', models.ImageField(upload_to='botavatar/')),
                ('chat_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_description', models.TextField(max_length=2048)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('chats', models.FileField(upload_to='chats/')),
                ('personas', models.FileField(upload_to='personas/')),
            ],
        ),
    ]
