# Generated by Django 5.1.6 on 2025-04-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_chatbots_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbots',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
