# Generated by Django 5.1.6 on 2025-03-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_botdata_personas_userdata_delete_bots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('sent_time', models.DateTimeField(auto_now=True)),
                ('chat_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='botdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='botdata',
            name='first_message',
            field=models.TextField(default=' ', max_length=2048),
        ),
        migrations.AddField(
            model_name='botdata',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='botdata',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botdata',
            name='scenario',
            field=models.TextField(default=' ', max_length=4096),
        ),
        migrations.AlterField(
            model_name='botdata',
            name='botname',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
