# Generated by Django 5.1.6 on 2025-05-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_chatbots_belongs_to_alter_personas_belongs_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbots',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
